spring:
  jpa:
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/awscite?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 6000s

# 数据库




